spring.datasource.url=jdbc:postgresql://localhost:5432/bugboardDB
spring.datasource.username=postgres
spring.datasource.password=manuel
spring.jpa.hibernate.ddl-auto=update

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.eu-south-1.amazonaws.com/eu-south-1_aA4G67UT3
spring.profiles.active=prod

