spring.datasource.url=jdbc:postgresql://localhost:5432/bugboardDB
spring.datasource.username=postgres
spring.datasource.password=manuel
spring.jpa.hibernate.ddl-auto=update
spring.profiles.active=dev

